### ISSUE TITLE
Divs

### ISSUE THREAD

**Issue by mikebutts** [k-romero/prj-rev-bwfs-dasmoto#1]
![image](https://user-images.githubusercontent.com/8017734/36095865-e9c00996-0fc1-11e8-89f6-fd2b1e47f1a2.png)

Good use of divs they keep your code organized and easy to read, looks like you forgot to close one.

**Comment by k-romero** [comment]
Yea I've been trying to get in the habit of writing out beginning and closing tags before filling in but i must have missed one. Could've swore Atom had the option to tab autofill start/end tags.

thanks
