### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [k-romero/prj-rev-bwfs-dasmoto#4]
Meets Expectations

Good job on this project it looks just like the spec. The code was neat and organized which made reading it easy. The only small error I found was the missing div tag which just keep an eye out for. I also mentioned using relative paths for resources in the next project, also keep an eye out for using caps. Using caps is fine in your directories just keep in mind you have to keep them all the same, so don't mix in lowercase and uppercase as forgetting to link it correctly (Resource/Images/image.jpg) for example linking this with a lower case R when it supposed to be uppercase will cause issues on some browsers. Great Job! Next, try to spice up the page, maybe add a background image for the header or some colors to the divs. Coolors.co has some cool schemes you can check out. Another idea is centering the  image and text so it's not all left aligned.

**Comment by k-romero** [comment]
Thanks for the feedback.

I'll have to keep an eye out for the tags and start using relative paths moving forward. I wasn't aware that we were supposed to elaborate on the design but if that's the case then I'm game. It seemed to me that this was mostly a "test" on everything we had learned/a good way to start using chrome dev tools.

I'll step it up next time.
